name: Trigger auto deployment for xlwings-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/xlwings-server-AutoDeployTrigger-f5e00418-9c6c-4441-945e-603199438eae.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.XLWINGSSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XLWINGSSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XLWINGSSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.XLWINGSSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.XLWINGSSERVER_REGISTRY_PASSWORD }}
          containerAppName: xlwings-server
          resourceGroup: xlwings-server-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


